### ISSUE TITLE
Onetimesecret Repo

### ISSUE THREAD

**Issue by gstw7** [mcrmonkey/docker-onetimesecret#1]
Hello, could you pass the files from this link? I can't download them.
Or tell me which branch you used from the official onetimesecret repository.
https://github.com/onetimesecret/onetimesecret/archive/master.zip

https://github.com/mcrmonkey/docker-onetimesecret/blob/master/Dockerfile#L6

**Comment by mcrmonkey** [comment]
Ah looks like the OTS repo switched from `master` to `main` as the name of the main branch

This will need to change to: https://github.com/onetimesecret/onetimesecret/archive/refs/heads/main.zip to pull from the same place...

**Comment by mcrmonkey** [comment]
Hopefully this should be fixed in the container now

Could you give it a try again ?

**Comment by gstw7** [comment]
it worked! Thanks!
